# travis configuration file
# Copyright 2018 Ilya Shipitsin <chipitsine@gmail.com>
#                Nicolas Mora <mail@babelouest.org>
sudo: required

language: c

addons:
  apt:
    packages: [ libmicrohttpd-dev, libjansson-dev, check, libsubunit-dev, cppcheck ]

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - env: LABEL=cppcheck
      os: linux
      script:
        - cppcheck --force --enable=warning,missingInclude --error-exitcode=1 . >build.log 2>&1 || (cat build.log && exit 1)

script:
  - mkdir build && cd build
  - cmake -DWITH_JOURNALD=off -DBUILD_ULFIUS_TESTING=on ..
  - make
  - sudo make install
  - make test
  - cd .. && make
  - cd example_programs
  - mkdir build && cd build
  - cmake ...
  - make
  - cd .. && make
