# travis configuration file
# Copyright 2018 Ilya Shipitsin <chipitsine@gmail.com>
#                Nicolas Mora <mail@babelouest.org>
sudo: required

language: c

addons:
  apt:
    packages: [ libmicrohttpd-dev, libjansson-dev, check, libsubunit-dev, cppcheck ]

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - env: LABEL=cppcheck
      os: linux
      script:
        - cppcheck --force --enable=warning,missingInclude --error-exitcode=1 . >build.log 2>&1 || (cat build.log && exit 1)

script:
  - mkdir build
  - mkdir example_programs/build
  - cd build
  - cmake -DWITH_JOURNALD=off -DBUILD_ULFIUS_TESTING=on ..
  - make test package
  - sudo make install
  - cd ../example_programs/build
  - rm -rf * && cmake ..
  - make
  - cd ../../build
  - rm -rf * && cmake -DWITH_JOURNALD=off -DBUILD_ULFIUS_TESTING=on -DWITH_WEBSOCKET=off -DWITH_JANSSON=off -DWITH_CURL=off ..
  - make package
  - sudo make install
  - cd ../example_programs/build
  - rm -rf * && cmake ..
  - make
  - cd ../../build
  - rm -rf * && cmake -DWITH_JOURNALD=off -DBUILD_ULFIUS_TESTING=on -DWITH_WEBSOCKET=off -DWITH_JANSSON=off -DWITH_CURL=on ..
  - make package
  - sudo make install
  - cd ../example_programs/build
  - rm -rf * && cmake ..
  - make
  - cd ../../build
  - rm -rf * && cmake -DWITH_JOURNALD=off -DBUILD_ULFIUS_TESTING=on -DWITH_WEBSOCKET=off -DWITH_JANSSON=on -DWITH_CURL=off ..
  - make package
  - sudo make install
  - cd ../example_programs/build
  - rm -rf * && cmake ..
  - make
  - cd ../../build
  - rm -rf * && cmake -DWITH_JOURNALD=off -DBUILD_ULFIUS_TESTING=on -DWITH_WEBSOCKET=off -DWITH_JANSSON=on -DWITH_CURL=on ..
  - make package
  - sudo make install
  - cd ../example_programs/build
  - rm -rf * && cmake ..
  - make
  - cd ../../build
  - rm -rf * && cmake -DWITH_JOURNALD=off -DBUILD_ULFIUS_TESTING=on -DWITH_WEBSOCKET=on -DWITH_JANSSON=off -DWITH_CURL=off ..
  - make package
  - sudo make install
  - cd ../example_programs/build
  - rm -rf * && cmake ..
  - make
  - cd ../../build
  - rm -rf * && cmake -DWITH_JOURNALD=off -DBUILD_ULFIUS_TESTING=on -DWITH_WEBSOCKET=on -DWITH_JANSSON=off -DWITH_CURL=on ..
  - make package
  - sudo make install
  - cd ../example_programs/build
  - rm -rf * && cmake ..
  - make
  - cd ../../build
  - rm -rf * && cmake -DWITH_JOURNALD=off -DBUILD_ULFIUS_TESTING=on -DWITH_WEBSOCKET=on -DWITH_JANSSON=on -DWITH_CURL=off ..
  - make package
  - sudo make install
  - cd ../example_programs/build
  - rm -rf * && cmake ..
  - make
  - cd ../../build
  - rm -rf * && cmake -DWITH_JOURNALD=off -DBUILD_ULFIUS_TESTING=on -DWITH_WEBSOCKET=on -DWITH_JANSSON=on -DWITH_CURL=on ..
  - sudo make install
  - make package
  - cd ../example_programs/build
  - make
